apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: demo
spec:
  containers:
  - name: my-container
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      timeoutSeconds: 5
